(() => {
  'use strict';
  const $ = (s) => document.querySelector(s);
  const $$ = (s) => [...document.querySelectorAll(s)];
  const chapters = $$('.chapter');
  let presentation = false;
  let presentIndex = 0;
  let scenario = 'business';
  let flowIndex = 0;
  let activeProblem = 0;
  let activeMethod = 0;

  const problems = [
    {name: 'Mensagens chegam. O histórico se perde.', description: 'O cidadão ou cliente fala com a organização, mas a demanda depende de alguém lembrar de encaminhar, registrar e responder.', outcome: 'Canais, registro, responsável e acompanhamento em um único fluxo.'},
    {name: 'Sua equipe trabalha duas vezes no mesmo assunto.', description: 'Copiar dados, repassar mensagens e atualizar planilhas consome o tempo que deveria ser dedicado às decisões e às pessoas.', outcome: 'Etapas repetitivas identificadas e conectadas, com supervisão onde importa.'},
    {name: 'Há relatórios. Falta enxergar o que está acontecendo.', description: 'A informação existe, mas está dispersa em canais e sistemas. O gestor descobre o atraso quando ele já gerou reclamação.', outcome: 'Indicadores e andamento visíveis para quem precisa agir.'},
    {name: 'A campanha funciona. A operação não acompanha.', description: 'A comunicação atrai atenção, mas os canais não registram interesse, o acompanhamento falha e a experiência se interrompe.', outcome: 'Marca, aquisição, atendimento e relacionamento desenhados como uma jornada.'}
  ];
  const methods = [
    {letter:'A', stage:'ETAPA 01 / ANÁLISE', headline:'Antes de construir, descobrimos o que precisa mudar.', body:'Mapeamos a jornada, os responsáveis, os canais e as rupturas que custam tempo, qualidade ou oportunidades.', deliverable:'Diagnóstico ADA com mapa de gargalos e prioridades.'},
    {letter:'D', stage:'ETAPA 02 / ARQUITETURA', headline:'Desenhamos o sistema para o contexto real da organização.', body:'Definimos fluxos, responsáveis, dados, comunicação, integrações e indicadores antes de escolher a tecnologia.', deliverable:'Blueprint ADA com arquitetura, escopo e plano de implantação.'},
    {letter:'A', stage:'ETAPA 03 / EXECUÇÃO', headline:'Implantamos, acompanhamos e melhoramos o que importa.', body:'Colocamos a solução em operação, preparamos as pessoas, medimos o uso e evoluímos com base em evidências.', deliverable:'Implantação ADA seguida de operação e evolução contínua.'}
  ];
  const flowData = {
    business: [
      {head:'Tudo começa com uma mensagem.', sender:'Cliente', channel:'WhatsApp · mensagem recebida', quote:'“Olá! Preciso de informações sobre o serviço e quero falar com alguém.”', trace:'Canal identificado', next:'Criar contexto para que a conversa não se perca.', explain:'A mensagem entra pelo canal escolhido. O próximo passo é organizar o que foi solicitado.'},
      {head:'O interesse vira registro, não esquecimento.', sender:'Cadastro de relacionamento', channel:'Contexto · demanda identificada', quote:'“Interesse: conhecer o serviço. Canal: WhatsApp. Próxima ação: triagem.”', trace:'Registro estruturado', next:'Associar a demanda a um responsável e preservar o histórico.', explain:'A organização deixa de depender de mensagens soltas e passa a ter contexto acessível.'},
      {head:'A conversa chega à pessoa certa.', sender:'Equipe de atendimento', channel:'Responsável · tarefa atribuída', quote:'“Novo contato com interesse no serviço. Histórico e contexto disponíveis.”', trace:'Responsável identificado', next:'Atender com contexto e critérios definidos pela operação.', explain:'A automação organiza a passagem, mas a equipe mantém o controle.'},
      {head:'O acompanhamento continua depois da resposta.', sender:'Relacionamento', channel:'Próxima ação · acompanhamento', quote:'“Verificar andamento, retomar a conversa quando apropriado e registrar o desfecho.”', trace:'Etapas com acompanhamento', next:'Evitar que oportunidades desapareçam entre uma conversa e outra.', explain:'O fluxo pode combinar lembretes, automações e intervenção humana, conforme o projeto.'},
      {head:'Quem decide passa a enxergar o processo.', sender:'Visão gerencial', channel:'Painel · atividade organizada', quote:'“Demandas por etapa, responsáveis, pendências e oportunidades em acompanhamento.”', trace:'Visibilidade operacional', next:'Priorizar melhorias com base no que está acontecendo.', explain:'A liderança acompanha indicadores definidos para sua operação. Esta tela não exibe dados reais.'}
    ],
    gov: [
      {head:'O cidadão registra uma necessidade.', sender:'Cidadão', channel:'Canal oficial · solicitação recebida', quote:'“A luminária da minha rua está apagada. Como acompanho o pedido?”', trace:'Demanda identificada', next:'Registrar o pedido sem perder a informação de origem.', explain:'A entrada digital pode orientar o cidadão e estruturar a solicitação, conforme os canais oficiais.'},
      {head:'A solicitação ganha contexto e protocolo.', sender:'Registro de demanda', channel:'Serviço · iluminação pública', quote:'“Tipo: iluminação. Local informado pelo cidadão. Dados mínimos para triagem.”', trace:'Registro estruturado', next:'Encaminhar sem exigir que o cidadão repita tudo.', explain:'O fluxo coleta o necessário e preserva as informações de cada atendimento.'},
      {head:'A secretaria responsável recebe o pedido.', sender:'Equipe responsável', channel:'Encaminhamento · atribuição', quote:'“Solicitação recebida para triagem. Equipe e prazo dependem da rotina municipal.”', trace:'Responsável identificado', next:'Acompanhar o encaminhamento dentro do processo da prefeitura.', explain:'A ADA organiza o fluxo. A execução e as decisões administrativas continuam com os servidores responsáveis.'},
      {head:'O cidadão acompanha o andamento.', sender:'Acompanhamento', channel:'Status · retorno ao cidadão', quote:'“Solicitação em acompanhamento. Atualização registrada pela equipe competente.”', trace:'Acompanhamento registrado', next:'Reduzir perda de contexto e orientar o retorno pelo canal adequado.', explain:'Mudanças de status dependem do processo real e da atualização das equipes.'},
      {head:'A gestão identifica o que está pendente.', sender:'Painel de gestão', channel:'Indicadores · acompanhamento', quote:'“Demandas por tipo, secretaria, bairro e etapa, conforme dados autorizados.”', trace:'Visão de gestão', next:'Apoiar a priorização de serviços e a prestação de informações.', explain:'A visualização é ilustrativa. Cada implantação exige definição de acesso, proteção de dados e governança.'}
    ]
  };

  function setProblem(n){activeProblem=n;const p=problems[n];$$('.problem-trigger').forEach((b,i)=>{b.classList.toggle('is-active',n===i);b.setAttribute('aria-pressed',String(n===i));});$('#problemCounter').textContent=`GARGALO / ${String(n+1).padStart(2,'0')}`;$('#problemTitle').textContent=p.name;$('#problemDescription').textContent=p.description;$('#problemOutcome').textContent=p.outcome;}
  $$('.problem-trigger').forEach(b=>b.addEventListener('click',()=>setProblem(Number(b.dataset.problem))));
  function setMethod(n){activeMethod=n;const m=methods[n];$$('.method-step').forEach((b,i)=>{b.classList.toggle('is-active',n===i);b.setAttribute('aria-selected',String(n===i));});$('#methodLetter').textContent=m.letter;$('#methodStage').textContent=m.stage;$('#methodHeadline').textContent=m.headline;$('#methodBody').textContent=m.body;$('#methodDeliverable').textContent=m.deliverable;}
  $$('.method-step').forEach(b=>b.addEventListener('click',()=>setMethod(Number(b.dataset.method))));
  function setFlow(n){flowIndex=n;const d=flowData[scenario][n];$$('.flow-step').forEach((b,i)=>{b.classList.toggle('is-active',n===i);b.setAttribute('aria-pressed',String(n===i));});$('#screenScene').textContent=scenario==='gov'?'PREFEITURA':'EMPRESA';$('#flowHeadline').textContent=d.head;$('#flowPill').textContent=`${String(n+1).padStart(2,'0')} / ${['ENTRADA','REGISTRO','EQUIPE','RETORNO','GESTÃO'][n]}`;$('#flowSender').textContent=d.sender;$('#flowChannel').textContent=d.channel;$('#flowQuote').textContent=d.quote;$('#flowTrace').textContent=d.trace;$('#flowNext').textContent=d.next;$('#flowExplain').textContent=d.explain;$('#flowNextButton').innerHTML=n===4?'Rever o fluxo <span aria-hidden="true">↺</span>':'Próxima etapa <span aria-hidden="true">→</span>';}
  $$('.flow-step').forEach(b=>b.addEventListener('click',()=>setFlow(Number(b.dataset.flow))));
  $$('.switch-option').forEach(b=>b.addEventListener('click',()=>{scenario=b.dataset.scenario;$$('.switch-option').forEach(o=>{const on=o===b;o.classList.toggle('is-active',on);o.setAttribute('aria-pressed',String(on));});setFlow(0);}));
  $('#flowNextButton').addEventListener('click',()=>setFlow((flowIndex+1)%5));

  // O modo de apresentação percorre os mesmos capítulos, sem duplicar conteúdo.
  const modeToggle=$('#modeToggle');const modeLabel=$('#modeToggleLabel');const presentControls=$('#presentationControls');
  function updatePresent(){chapters.forEach((c,i)=>c.classList.toggle('is-presenting',i===presentIndex));$('#presentSection').textContent=chapters[presentIndex].dataset.title.toUpperCase();$('#presentCount').textContent=`${String(presentIndex+1).padStart(2,'0')} / ${String(chapters.length).padStart(2,'0')}`;$('#presentPrev').disabled=presentIndex===0;$('#presentNext').disabled=presentIndex===chapters.length-1;window.scrollTo({top:0,behavior:'auto'});const url=new URL(location.href);url.searchParams.set('modo','apresentar');url.searchParams.set('cap',String(presentIndex+1));try{history.replaceState(null,'',url.pathname+url.search+url.hash);}catch(e){/* Visualização local sem histórico navegável. */}}
  function setPresent(on,index=presentIndex){presentation=on;document.body.classList.toggle('present-mode',on);modeToggle.setAttribute('aria-pressed',String(on));modeLabel.textContent=on?'Explorar':'Apresentar';modeToggle.title=on?'Voltar ao modo explorar':'Ativar modo apresentação';presentControls.hidden=!on;if(on){presentIndex=Math.max(0,Math.min(chapters.length-1,index));updatePresent();}else{chapters.forEach(c=>c.classList.remove('is-presenting'));const url=new URL(location.href);url.searchParams.delete('modo');url.searchParams.delete('cap');try{history.replaceState(null,'',url.pathname+url.search+url.hash);}catch(e){/* Visualização local sem histórico navegável. */}const target=chapters[presentIndex];requestAnimationFrame(()=>target.scrollIntoView({behavior:'auto',block:'start'}));}}
  modeToggle.addEventListener('click',()=>setPresent(!presentation, presentation?presentIndex:Math.max(0,chapters.findIndex(c=>{const r=c.getBoundingClientRect();return r.top<=window.innerHeight*.48&&r.bottom>window.innerHeight*.48;}))));
  $('#presentExit').addEventListener('click',()=>setPresent(false));$('#presentPrev').addEventListener('click',()=>{if(presentIndex>0){presentIndex--;updatePresent();}});$('#presentNext').addEventListener('click',()=>{if(presentIndex<chapters.length-1){presentIndex++;updatePresent();}});
  document.addEventListener('keydown',e=>{if(!presentation||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowRight'||e.key==='PageDown'){if(presentIndex<chapters.length-1){presentIndex++;updatePresent();e.preventDefault();}}else if(e.key==='ArrowLeft'||e.key==='PageUp'){if(presentIndex>0){presentIndex--;updatePresent();e.preventDefault();}}else if(e.key==='Escape'){setPresent(false);}});
  const params=new URLSearchParams(location.search);if(params.get('modo')==='apresentar')setPresent(true,Math.max(0,Number(params.get('cap')||'1')-1));
  // Links de capítulo preservam o modo; apresentação não usa navegação de slide por iframe.
  $$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=$(a.getAttribute('href'));if(!target)return;if(presentation){const idx=chapters.indexOf(target);if(idx>=0){e.preventDefault();presentIndex=idx;updatePresent();}}const menu=$('#mainNav');menu.classList.remove('is-open');$('#menuToggle').setAttribute('aria-expanded','false');$('#menuToggle').setAttribute('aria-label','Abrir menu');}));
  $('#menuToggle').addEventListener('click',()=>{const menu=$('#mainNav');const open=menu.classList.toggle('is-open');$('#menuToggle').setAttribute('aria-expanded',String(open));$('#menuToggle').setAttribute('aria-label',open?'Fechar menu':'Abrir menu');});
  if('IntersectionObserver'in window){const revealObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');revealObserver.unobserve(e.target);}})},{threshold:.075,rootMargin:'0px 0px -25px 0px'});$$('.reveal').forEach(el=>revealObserver.observe(el));}else{$$('.reveal').forEach(el=>el.classList.add('is-visible'));}
  let scrolling=false;function onScroll(){if(presentation)return;if(scrolling)return;scrolling=true;requestAnimationFrame(()=>{const total=Math.max(1,document.documentElement.scrollHeight-innerHeight);$('#pageProgress').style.width=`${Math.min(100,scrollY/total*100)}%`;const mark=innerHeight*.33;let current=chapters[0];chapters.forEach(c=>{const b=c.getBoundingClientRect();if(b.top<=mark&&b.bottom>mark)current=c;});$$('.main-nav a').forEach(a=>a.classList.toggle('is-current',a.getAttribute('href')==='#'+current.id));scrolling=false;});}window.addEventListener('scroll',onScroll,{passive:true});onScroll();

  // O formulário NÃO envia para nenhum backend inexistente: gera um briefing copiável.
  let prepared='';const form=$('#diagnosticForm');
  form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);prepared=`DIAGNÓSTICO ADA | BRIEFING INICIAL\n\nNome: ${data.get('name')}\nOrganização: ${data.get('organization')}\nContexto: ${data.get('type')}\nGargalo principal: ${data.get('pain')}\n\nPróximo passo sugerido: conversa de diagnóstico para entender o processo, identificar responsáveis e definir prioridades.`;$('#briefText').textContent=prepared;form.hidden=true;$('#briefResult').hidden=false;$('#copyStatus').textContent='';$('#briefResult').scrollIntoView({block:'nearest',behavior:'smooth'});});
  $('#editBrief').addEventListener('click',()=>{form.hidden=false;$('#briefResult').hidden=true;$('#fieldPain').focus();});
  $('#copyBrief').addEventListener('click',async()=>{const status=$('#copyStatus');try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(prepared);}else{const ta=document.createElement('textarea');ta.value=prepared;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();if(!ok)throw new Error('clipboard');}status.textContent='Briefing copiado. Compartilhe com a ADA pelo canal comercial oficial.';}catch(err){status.textContent='Não foi possível copiar automaticamente. Selecione e copie o texto acima.';}});
})();
